name: CI
  
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', 'pypy-2.7', 'pypy-3.7', 'pyston']
        os: [ubuntu-latest]
        architecture: ["x64"]
        include:
          - python-version: '3.4'
            os: ubuntu-18.04
            architecture: "x64"
          - python-version: '3.9'
            os: macos-latest
            architecture: "x64"
          - python-version: '3.9'
            os: windows-latest
            architecture: "x64"
          - python-version: '3.9'
            os: windows-latest
            architecture: "x86"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodule
      run: |
        git submodule init
        git submodule update
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.python-version != 'pyston' }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Set up Pyston
      if: ${{ matrix.python-version == 'pyston' }}
      run: |
        wget -O pyston.deb https://github.com/pyston/pyston/releases/download/pyston_2.3.2/pyston_2.3.2_20.04.deb
        sudo apt update
        sudo apt install -y ./pyston.deb
        sudo ln -sf pyston /usr/bin/python
        sudo chown -RH $(whoami) $(python -c 'import os,inspect;print(os.path.dirname(inspect.getfile(inspect)))')
        sudo chown -hRH $(whoami) /usr/bin
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest wheel pybind11
    # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install
      run: |
        python setup.py install
    - name: Test
      run: |
        pytest -v test
