name: manylinux
  
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodule
      run: |
        git submodule init
        git submodule update
    - name: Build wheel (1)
      uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux1_x86_64
      with:
        python-versions: "cp27-cp27mu cp35-cp35m cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39"
    - name: Build wheel (2)
      uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64
      with:
        python-versions: "cp310-cp310 pp37-pypy37_pp73 pp38-pypy38_pp73 pp39-pypy39_pp73"
    - name: Remove non-manylinux wheels
      run: |
        sudo rm -f dist/*-linux*.whl
        sudo rm -f dist/*manylinux*manylinux*manylinux*manylinux*.whl
    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: dist
